version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres_1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5400:5432
    environment:
         - POSTGRES_PASSWORD=mydb
         - POSTGRES_USER=postgres
         - POSTGRES_DB=postgres
    restart: unless-stopped
# APP*****************************************
  springbootapp:
    image: anujakanade/springrepo_04:savingsa
    network_mode: bridge
    container_name: savingsa-microservice-docker
    expose:
      - 8081
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data: